# Generated by Django 6.0.5 on 2026-05-09 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('api_keys', '0001_initial'),
        ('usage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='accounts.organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uploaded file',
                'verbose_name_plural': 'uploaded files',
                'db_table': 'uploaded_files',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_input', models.TextField(blank=True, null=True)),
                ('modality', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('text', 'Text')], max_length=20)),
                ('bits_charged', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('trust_score', models.IntegerField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('authentic', 'Authentic'), ('suspicious', 'Suspicious'), ('manipulated', 'Manipulated'), ('inconclusive', 'Inconclusive')], max_length=20, null=True)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('api_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='usage.apicall')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='api_keys.apikey')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='accounts.organization')),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='verifications.uploadedfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verification',
                'verbose_name_plural': 'verifications',
                'db_table': 'verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('ml_endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('ml_response_raw', models.JSONField(blank=True, default=dict)),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='verifications.verification')),
            ],
            options={
                'verbose_name': 'verification job',
                'verbose_name_plural': 'verification jobs',
                'db_table': 'verification_jobs',
            },
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['owner_user'], name='idx_file_owner_user'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['owner_organization'], name='idx_file_owner_org'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['sha256'], name='idx_file_sha256'),
        ),
        migrations.AddConstraint(
            model_name='uploadedfile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_organization__isnull', True), ('owner_user__isnull', False)), models.Q(('owner_organization__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='file_xor_owner'),
        ),
        migrations.AddConstraint(
            model_name='uploadedfile',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='file_positive_size'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['user', '-created_at'], name='idx_verif_user_recent'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', '-created_at'], name='idx_verif_org_recent'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(condition=models.Q(('status__in', ['queued', 'analyzing'])), fields=['status'], name='idx_verif_active_queue'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('user__isnull', False)), models.Q(('organization__isnull', False), ('user__isnull', True)), _connector='OR'), name='verif_xor_owner'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(condition=models.Q(('trust_score__isnull', True), models.Q(('trust_score__gte', 0), ('trust_score__lte', 100)), _connector='OR'), name='verif_trust_score_range'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(condition=models.Q(('api_key__isnull', True), ('organization__isnull', False), _connector='OR'), name='verif_api_key_requires_org'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(condition=models.Q(('api_call__isnull', True), ('organization__isnull', False), _connector='OR'), name='verif_api_call_requires_org'),
        ),
        migrations.AddIndex(
            model_name='verificationjob',
            index=models.Index(fields=['celery_task_id'], name='idx_job_celery_task'),
        ),
    ]
