# Generated by Django 6.0.5 on 2026-05-11 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='source_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_verifications', to='connectors.connectorevent'),
        ),
        migrations.AddField(
            model_name='verification',
            name='source_install',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='connectors.connectorinstall'),
        ),
    ]
