# Generated by Django 6.0.5 on 2026-05-13 23:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_verification_source_verification_source_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVerificationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of the file contents.', max_length=64, unique=True)),
                ('trust_score', models.IntegerField(help_text='Cached trust score (0–100).')),
                ('result_summary', models.JSONField(default=dict, help_text='Cached mapped result_summary (same schema as Verification.result_summary).')),
                ('ml_response_raw', models.JSONField(default=dict, help_text='Full ML service response payload.')),
                ('original_filename', models.CharField(blank=True, default='', help_text='Filename of the first file that created this cache entry.', max_length=255)),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='Number of times this cache entry has been reused.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'image verification cache entry',
                'verbose_name_plural': 'image verification cache entries',
                'db_table': 'image_verification_cache',
            },
        ),
    ]
