# Generated by Django 6.0.5 on 2026-05-09 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('recurring_charge_naira', models.BigIntegerField(default=0, help_text='Whole-naira amount Squad debits per period. 0 for free.')),
                ('monthly_grant_bits', models.BigIntegerField(help_text='Bit tokens credited to the user wallet at the start of each period.')),
                ('billing_interval', models.CharField(choices=[('none', 'None'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'db_table': 'plans',
                'constraints': [models.CheckConstraint(condition=models.Q(('monthly_grant_bits__gte', 0)), name='plan_non_negative_grant')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('paused', 'Paused')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('squad_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('squad_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='billing.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_sub_user_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'past_due', 'paused'])), fields=('user',), name='one_active_sub_per_user')],
            },
        ),
    ]
