# Generated by Django 6.0.5 on 2026-05-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='squad_card_token_id',
            field=models.CharField(blank=True, help_text='Card token from Squad for recurring charges (returned via webhook).', max_length=255, null=True),
        ),
    ]
