# Generated by Django 6.0.5 on 2026-05-09 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('modality', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('text', 'Text')], max_length=20, null=True)),
                ('http_status', models.IntegerField()),
                ('bits_charged', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField()),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_calls', to='api_keys.apikey')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_calls', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'API call',
                'verbose_name_plural': 'API calls',
                'db_table': 'api_calls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='idx_apicall_org_recent'), models.Index(fields=['api_key', '-created_at'], name='idx_apicall_key_recent')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('api_key', 'idempotency_key'), name='unique_idempotency_per_key')],
            },
        ),
    ]
