# Generated by Django 6.0.5 on 2026-05-09 19:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('squad', 'Squad')], max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'webhook event',
                'verbose_name_plural': 'webhook events',
                'db_table': 'webhook_events',
                'indexes': [models.Index(fields=['status', 'received_at'], name='idx_webhook_status_received')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source', 'external_id'), name='unique_source_external_id')],
            },
        ),
    ]
