# Generated by Django 6.0.5 on 2026-05-11 16:39

import apps.connectors.crypto
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_add_organization_description'),
        ('verifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_url', models.URLField(blank=True, default='', max_length=500)),
                ('category', models.CharField(choices=[('email', 'Email'), ('chat', 'Chat'), ('social', 'Social'), ('productivity', 'Productivity'), ('browser', 'Browser'), ('other', 'Other')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('coming_soon', 'Coming soon'), ('alpha', 'Alpha'), ('beta', 'Beta'), ('ga', 'General availability')], default='coming_soon', max_length=16)),
                ('auth_type', models.CharField(choices=[('oauth2', 'OAuth2'), ('bot_token', 'Bot token'), ('webhook_signature', 'Webhook signature'), ('api_key', 'API key')], max_length=32)),
                ('supports_b2c', models.BooleanField(default=True)),
                ('supports_b2b', models.BooleanField(default=True)),
                ('supports_auto_verify', models.BooleanField(default=False)),
                ('settings_schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'connector_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorInstall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_account_id', models.CharField(max_length=128)),
                ('external_account_label', models.CharField(blank=True, default='', max_length=255)),
                ('credentials', apps.connectors.crypto.EncryptedJSONField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_installs', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_installs', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='connectors.connectortype')),
            ],
            options={
                'db_table': 'connector_installs',
            },
        ),
        migrations.CreateModel(
            name='ConnectorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('verifications', models.ManyToManyField(blank=True, related_name='connector_events_m2m', to='verifications.verification')),
                ('install', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='connectors.connectorinstall')),
            ],
            options={
                'db_table': 'connector_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound')], default='outbound', max_length=16)),
                ('kind', models.CharField(max_length=32)),
                ('external_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='connectors.connectorevent')),
                ('install', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='connectors.connectorinstall')),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_messages', to='verifications.verification')),
            ],
            options={
                'db_table': 'connector_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorTypeInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='connectors.connectortype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connector_type_interests',
            },
        ),
        migrations.AddConstraint(
            model_name='connectorevent',
            constraint=models.UniqueConstraint(fields=('install', 'external_event_id'), name='connector_event_idempotent'),
        ),
        migrations.AddIndex(
            model_name='connectorinstall',
            index=models.Index(fields=['type', 'is_active'], name='idx_conn_install_type_active'),
        ),
        migrations.AddConstraint(
            model_name='connectorinstall',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('user__isnull', False)), models.Q(('organization__isnull', False), ('user__isnull', True)), _connector='OR'), name='connector_install_xor_owner'),
        ),
        migrations.AddConstraint(
            model_name='connectorinstall',
            constraint=models.UniqueConstraint(fields=('type', 'external_account_id'), name='connector_install_unique_external'),
        ),
        migrations.AddConstraint(
            model_name='connectortypeinterest',
            constraint=models.UniqueConstraint(fields=('connector_type', 'user'), name='connector_interest_unique_user_type'),
        ),
    ]
