# Generated by Django 6.0.5 on 2026-05-09 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('webhooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_bits', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_wallet', to='accounts.organization')),
                ('owner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token wallet',
                'verbose_name_plural': 'token wallets',
                'db_table': 'token_wallets',
            },
        ),
        migrations.CreateModel(
            name='TokenLedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delta_bits', models.BigIntegerField()),
                ('balance_after_bits', models.BigIntegerField()),
                ('entry_type', models.CharField(choices=[('subscription_grant', 'Subscription Grant'), ('period_reset', 'Period Reset'), ('topup', 'Top-Up'), ('usage', 'Usage'), ('adjustment', 'Adjustment'), ('refund', 'Refund')], max_length=30)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='bits.tokenwallet')),
            ],
            options={
                'verbose_name': 'token ledger entry',
                'verbose_name_plural': 'token ledger entries',
                'db_table': 'token_ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('squad_account_reference', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_account', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'virtual account',
                'verbose_name_plural': 'virtual accounts',
                'db_table': 'virtual_accounts',
            },
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_naira', models.BigIntegerField()),
                ('bits_credited', models.BigIntegerField()),
                ('rate_naira_per_bit', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('squad_transaction_reference', models.CharField(max_length=255, unique=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='accounts.organization')),
                ('webhook_event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='topups', to='webhooks.webhookevent')),
                ('virtual_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='topups', to='bits.virtualaccount')),
            ],
            options={
                'verbose_name': 'top-up',
                'verbose_name_plural': 'top-ups',
                'db_table': 'top_ups',
            },
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_organization__isnull', True), ('owner_user__isnull', False)), models.Q(('owner_organization__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='wallet_xor_owner'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance_bits__gte', 0)), name='wallet_non_negative_balance'),
        ),
        migrations.AddIndex(
            model_name='tokenledgerentry',
            index=models.Index(fields=['wallet', '-created_at'], name='idx_ledger_wallet_recent'),
        ),
        migrations.AddIndex(
            model_name='tokenledgerentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='idx_ledger_reference'),
        ),
        migrations.AddConstraint(
            model_name='tokenledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('delta_bits', 0), _negated=True), name='ledger_non_zero_delta'),
        ),
        migrations.AddConstraint(
            model_name='tokenledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after_bits__gte', 0)), name='ledger_non_negative_balance_after'),
        ),
        migrations.AddIndex(
            model_name='topup',
            index=models.Index(fields=['organization', '-created_at'], name='idx_topup_org_recent'),
        ),
        migrations.AddConstraint(
            model_name='topup',
            constraint=models.CheckConstraint(condition=models.Q(('amount_naira__gt', 0)), name='topup_positive_naira'),
        ),
        migrations.AddConstraint(
            model_name='topup',
            constraint=models.CheckConstraint(condition=models.Q(('bits_credited__gt', 0)), name='topup_positive_bits'),
        ),
        migrations.AddConstraint(
            model_name='topup',
            constraint=models.CheckConstraint(condition=models.Q(('rate_naira_per_bit__gt', 0)), name='topup_positive_rate'),
        ),
    ]
